package strings

const TYPE_ONBOARDING_REQUEST = "ONBOARDING_REQUEST"
const TYPE_ONBOARDING_RESPONSE = "ONBOARDING_RESPONSE"
const TYPE_GAME_STARTING_MESSAGE = "GAME_STARTING_MESSAGE"
const TYPE_PLAYER_TURN_MESSAGE = "PLAYER_TURN_MESSAGE"
const TYPE_MAKE_MOVE_MESSAGE = "MAKE_MOVE_MESSAGE"
const TYPE_ILLEGAL_MOVE_MESSAGE = "ILLEGAL_MOVE_MESSAGE"
const TYPE_ACCEPTED_MOVE_MESSAGE = "ACCEPTED_MOVE_MESSAGE"