package strings

const TYPE_ONBOARDING_REQUEST = "ONBOARDING_REQUEST"
const TYPE_ONBOARDING_RESPONSE = "ONBOARDING_RESPONSE"
const TYPE_GAME_STARTING_MESSAGE = "GAME_STARTING_MESSAGE"
const TYPE_PLAYER_TURN_MESSAGE = "PLAYER_TURN_MESSAGE"